name: Update Forked Repos

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # use version, that's on GH vscode
        cache: 'pip'
    - run: |
        pip install PyGithub==2.3.0

    - name: Run script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python your_script.py